### ISSUE TITLE
build issue while building openvslam

### ISSUE THREAD

**Issue by rahuldeo2047** [xdspacelab/openvslam#102]
Followed: https://openvslam.readthedocs.io/en/master/installation.html

There is no build error(s) at any other step(s) before this.

I get following error message in step "When building with support for SocketViewer".

Error msgs

`map_segment.proto:1:10: Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".
src/socket_publisher/CMakeFiles/socket_publisher.dir/build.make:62: recipe for target 'src/socket_publisher/map_segment.pb.cc' failed
make[2]: *** [src/socket_publisher/map_segment.pb.cc] Error 1
CMakeFiles/Makefile2:448: recipe for target 'src/socket_publisher/CMakeFiles/socket_publisher.dir/all' failed
make[1]: *** [src/socket_publisher/CMakeFiles/socket_publisher.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
`

system info
```
$uname -a
  Linux abcd 4.15.0-58-generic #64~16.04.1-Ubuntu SMP Wed Aug 7 14:10:35 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

$ protoc --version
 libprotoc 2.6.1

$ pkg-config --cflags protobuf 
 -pthread

$ pkg-config --cflags --libs protobuf 
  -pthread -I/usr/local/include -L/usr/local/lib -lprotobuf -pthread -lpthread


# I do have openCV installed with ROS-kinetic

$ pkg-config --cflags opencv
 Package opencv was not found in the pkg-config search path.
 Perhaps you should add the directory containing `opencv.pc'
 to the PKG_CONFIG_PATH environment variable
 No package 'opencv' found
```

**Comment by rahuldeo2047** [comment]
The Pangolin build is working great.

**Comment by shinsumicco** [comment]
It seems that the version of `protobuf` and `protoc` you use are too old.
Could you use the version 3.x of them, which can parse `proto3` schemes?

If you use Ubuntu 16.04, it is needed to build the newest protobuf from source.

```
wget -q https://github.com/google/protobuf/archive/v3.6.1.tar.gz
tar xf v3.6.1.tar.gz
cd protobuf-3.6.1
./autogen.sh
./configure \
    --prefix=/usr/local \
    --enable-static=no
make -j4
make install
```

**Comment by rahuldeo2047** [comment]
Hey, thank you for the reply.

I tried that and still protoc --version gives version 2 as mentioned in first comment.

**Comment by shinsumicco** [comment]
Dis you install `protoc` via apt?

Please try this then rebuild and reinstall protoc from souce as mentioned in my comment:
```
apt purge libprotobuf-dev protobuf-compiler
```

**Comment by rahuldeo2047** [comment]
ok will try that

**Comment by rahuldeo2047** [comment]
ref: https://github.com/xdspacelab/openvslam/issues/32

**Comment by shinsumicco** [comment]
@rahuldeo2047
Did you solved?

**Comment by rahuldeo2047** [comment]
I had to shift to Ubuntu 18.04 .
Now it is building and running fine.

**Comment by shinsumicco** [comment]
Thank you for the report. @rahuldeo2047
