### ISSUE TITLE
Errors in the g2o classes, windows 10.

### ISSUE THREAD

**Issue by antithing** [xdspacelab/openvslam#108]
I am building for windows 10, visual studio 2017, I am down to four errors, in the g2o classes, and I am not sure of the fix here.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2005	"public: virtual void __cdecl g2o::BaseEdge<2,class Eigen::Matrix<double,2,1,0,2,1> >::setMeasurement(class Eigen::Matrix<double,2,1,0,2,1> const &)" 
(?setMeasurement@?$BaseEdge@$01V?$Matrix@N$01$00$0A@$01$00@Eigen@@@g2o@@UEAAXAEBV?$Matrix@N$01$00$0A@$01$00@Eigen@@@Z) 
already defined in perspective_pose_opt_edge.obj	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2005	"public: virtual void __cdecl g2o::BaseEdge<3,class Eigen::Matrix<double,3,1,0,3,1> >::setMeasurement(class Eigen::Matrix<double,3,1,0,3,1> const &)" 
(?setMeasurement@?$BaseEdge@$02V?$Matrix@N$02$00$0A@$02$00@Eigen@@@g2o@@UEAAXAEBV?$Matrix@N$02$00$0A@$02$00@Eigen@@@Z) 
already defined in perspective_pose_opt_edge.obj

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2005	"public: virtual void __cdecl g2o::BaseEdge<7,struct g2o::Sim3>::setMeasurement(struct g2o::Sim3 const &)" 
(?setMeasurement@?$BaseEdge@$06USim3@g2o@@@g2o@@UEAAXAEBUSim3@2@@Z) already defined in graph_opt_edge.obj	

Severity	Code	Description	Project	File	Line	Suppression State
Error	LNK2005	"public: void __cdecl g2o::BaseVertex<7,struct g2o::Sim3>::setEstimate(struct g2o::Sim3 const &)" 
(?setEstimate@?$BaseVertex@$06USim3@g2o@@@g2o@@QEAAXAEBUSim3@2@@Z) already defined in graph_opt_edge.obj	
```

This looks to be the same issue as [28](https://github.com/xdspacelab/openvslam/issues/28)

But I do not understand the fix mentioned there. What can i do about these errors?
Thanks!

**Comment by shinsumicco** [comment]
Thank you for posting, @antithing.

We are currently working on the build on Windows.
Could you please wait until then?

We are very grateful if you post here any instructions you did for the build with Visual Studio.

**Comment by antithing** [comment]
Hi @shinsumicco, do you have an estimate for releasing the first windows version? 
I am happy to test for you if you need!

Thanks again.

**Comment by schweitzer** [comment]
Hello,

I've experimented the same issues (and many others) on msvc 2019.

This seems the same as in #28, but the I don't think that the mentioned workaround is a real fix.

For now I don't understand why msvc find multiple definitions in optimise/g2o module but I will keep trying, and I let you know if I find something interesting.

Furthermore to have a full windows 10 support you also need to remove (or to convert) all CXX_FLAGS in the main CMakeLists.txt, along with removing OpenMP support (msvc is stuck to version 2.0).

**Comment by rgolovanov** [comment]
Same linking errors. Did anybody fix it?

**Comment by antithing** [comment]
I tried for a while but could not get to the bottom of the g2o errors. I have never seen these issues with g2o before.

If anyone finds the fix please post it here!

**Comment by rgolovanov** [comment]
These errors mean multiple instantiation of template classes with same arguments (types) which are happened at g2o side and OpenVSLAM as well. Only one temporary workaround I found is to forcibly suppress these errors by adding linker argument `add_link_options(/FORCE:MULTIPLE)` but I've not tested library well yet, so be attentive.

**Comment by shinsumicco** [comment]
Dear all,
Sorry for the late reply, @antithing.
Temporarily I don't have access to Windows environment, so I cannot try to build OpenVSLAM on Windows at the moment.
Does the build problem seem to be caused by the multiple instantiation of template classes?

**Comment by rgolovanov** [comment]
@shinsumicco most probably the root cause is in multiple template instantiation with same template arguments. Let's see, e.g. `Error	LNK2005	"public: virtual void __cdecl g2o::BaseEdge<2,class Eigen::Matrix<double,2,1,0,2,1> >::setMeasurement(class Eigen::Matrix<double,2,1,0,2,1> const &)" 
(?setMeasurement@?$BaseEdge@$01V?$Matrix@N$01$00$0A@$01$00@Eigen@@@g2o@@UEAAXAEBV?$Matrix@N$01$00$0A@$01$00@Eigen@@@Z) 
already defined in perspective_pose_opt_edge.obj`

There are two instantiation of `g2o::BaseEdge<2,class Eigen::Matrix<double,2,1,0,2,1>>`:
* In **OpenVSLAM** (_...\openvslam\src\openvslam\optimize\g2o\se3\perspective_pose_opt_edge.h_):
```class mono_perspective_pose_opt_edge final : public ::g2o::BaseUnaryEdge<2, Vec2_t, shot_vertex>```
* and in **g2o** (g2o\types\slam2d\edge_xy_prior.h):
``` class G2O_TYPES_SLAM2D_API EdgeXYPrior : public BaseUnaryEdge<2, Vector2, VertexPointXY>```

Which leads to instantiation of same `BaseEdge` class:
`class BaseUnaryEdge : public BaseEdge<D,E>`

Absolutely same thing for other linking errors. You can find instantiation of template classes with equal template arguments.

**Comment by antithing** [comment]
I can confirm that by making the following changes the lib will build and run on windows 10, visual studio 2017.

#define _USE_MATH_DEFINES
#include <cmath>
 or #define M_PI in a few headers.

add include path for \SuiteSparse_config.h
add include path for g2o_config.h
added lapack and blas libs as dependencies

I also swapped the LinearSolverCSparse for LinearSolverCholmod, as i had some unresolved errors in CSparse.

However, using my own live stereo camera at 640 x 360, I see a frame time of around 110 ms. Much slower than it should be based on the paper.  Is there anything I can look at to speed this up?

Thanks!

**Comment by reunanen** [comment]
For the record: I, too, got OpenVSLAM built and running on Windows 10, Visual Studio 2017. In addition to the discussion above, found some very useful information [here](https://qiita.com/na0ki_ikeda/items/2310dc8dd70713de98e1) (in Japanese, but Google translation helps).

It did take quite a while to complete all the steps, though. Moreover, I'm not a big fan of CMake generated project files that have absolute paths all over. Therefore, I wanted to try to figure out a cleaner way of setting up a Visual Studio build, and eventually came up with [this](https://github.com/reunanen/openvslam-build-vs). So, if anyone wants to test this alternative approach, here are the instructions:

1. `git clone https://github.com/reunanen/openvslam-build-vs`
2. `cd openvslam-build-vs`
3. `git submodule update --init --recursive`
4. Open `openvslam.sln` (in repo root) in Visual Studio 2017
5. Build
6. Test as described [here](https://openvslam.readthedocs.io/en/master/simple_tutorial.html)

Out of the box, it'll expect that your processor has [AVX2](https://en.wikipedia.org/wiki/Advanced_Vector_Extensions#Advanced_Vector_Extensions_2). (This requirement is possible to relax, though – if anybody needs to run this on lower-end CPUs, please let me know.)

At any rate, the runtime speed seems to be ok, at least on my machine:
![test](https://user-images.githubusercontent.com/2297572/71645267-652c8600-2cde-11ea-991e-a7647ca977a8.gif)

Also, [all tests complete successfully](https://ci.appveyor.com/project/reunanen/openvslam-build-vs/builds/29852302#L2834).

Oh, and thanks a lot for this library, it looks really great!

**Comment by shinsumicco** [comment]
@antithing 
Would you try this?
https://github.com/shinsumicco/openvslam-on-msvc/
