### ISSUE TITLE
How to write the stereo config file(Intrinsic，Extrinsic parametres)

### ISSUE THREAD

**Issue by OldAAAA** [xdspacelab/openvslam#115]
Why there is only one camera model in the stereo camera config file.

![2019-09-14 20-40-46屏幕截图](https://user-images.githubusercontent.com/35156231/64908262-4e165800-d730-11e9-8236-8c01b4ffc5eb.png)

And i read the source code there is only one instance in the "config()" method.
![2019-09-14 20-37-45屏幕截图](https://user-images.githubusercontent.com/35156231/64908209-a4cf6200-d72f-11e9-995c-e4a4efc5e9bf.png)
I want to know how to write the stereo config file.

**Comment by JinglingZhu** [comment]
@OldAAAA Do you have the answer? I have the same question, would you please share with us.

**Comment by Gilaine** [comment]
do you an answer ?

**Comment by Gilaine** [comment]
Did you find an answer to it ?
