### ISSUE TITLE
Trying to build ROS nodes

### ISSUE THREAD

**Issue by griz1112** [xdspacelab/openvslam#119]
Getting this error trying to build the ROS nodes. openvslam/ros/src/openvslam/src/run_localization.cc:71:14: error: ‘class openvslam::system’ has no member named ‘track_for_monocular’

**Comment by ethanguo0327** [comment]
facing the same problem ...I have no idea,some body give any help?

**Comment by ricardoGrando** [comment]
Change 

SLAM.**track_for_monocular**(cv_bridge::toCvShare(msg, "bgr8")->image, timestamp, mask); 
to
SLAM.**feed_monocular_frame**(cv_bridge::toCvShare(msg, "bgr8")->image, timestamp, mask);

It will compile!

**Comment by ethanguo0327** [comment]
it works! thank u so much! @ricardoGrando

**Comment by shinsumicco** [comment]
Thank you for posting, @griz1112, @ethanguo0327, and @ricardoGrando.
I forgot to change the method names in the ROS module according to refactoring of  `openvslam::system` class.
I'll fix it soon.

**Comment by griz1112** [comment]
Thanks.
