### ISSUE TITLE
Can this be done in realtime?

### ISSUE THREAD

**Issue by Wsupatgiat** [xdspacelab/openvslam#127]
Hi, kinda new to this thing. Can this be employed to track location in realtime?

**Comment by vwvw** [comment]
Yes, see: https://github.com/xdspacelab/openvslam/blob/master/example/run_camera_localization.cc where openvslam use usb cameras.

**Comment by Wsupatgiat** [comment]
Thankyou.

**Comment by OmarLaz97** [comment]
can this be used with a smartphone camera sending video frames ?

**Comment by dimaxano** [comment]
@OmarLaz97 In theory, yes. But I think porting to iOS/Android platform is a non trivial task

**Comment by netgfx** [comment]
is there an example of how to format images send from mobile devices?
