### ISSUE TITLE
Is there any relative paper about this project?

### ISSUE THREAD

**Issue by biggoood** [xdspacelab/openvslam#15]
Hi,

I'm quite interested in this project, it's a brilliant work. Could you please recommend me some relative paper? or did you have a paper of this openvslam?

Thanks!

**Comment by kensakurada** [comment]
Thank you for your interest in our project. We will upload the preprint version of our OpenVSLAM paper in a week, so please wait until then.

**Comment by biggoood** [comment]
Great, thanks!

**Comment by BakhtawarRehman** [comment]
Hello) same question here) 
+ it has been 2 months since your post; so any chance of sharing the paper?

**Comment by feroze** [comment]
The preprint is available under https://github.com/xdspacelab/openvslam#citation
