### ISSUE TITLE
Does SLAM mean anything?

### ISSUE THREAD

**Issue by markfirmware** [xdspacelab/openvslam#160]

**Comment by moppius** [comment]
This Wikipedia page on [Simultaneous localization and mapping](https://en.wikipedia.org/wiki/Simultaneous_localization_and_mapping) is literally the top result if you search [Google](https://www.google.com) for SLAM.

@markfirmware, I find it difficult to believe that you are capable of opening a Github issue, but unable to search the internet for this information. Please don't open issues frivolously, it's a waste of everyone else's time.

**Comment by shinsumicco** [comment]
Thank you @moppius.
This is not an issue for this framework. Closed.
