### ISSUE TITLE
Will it faster than ORB_SLAM2 when doing stereo mapping?

### ISSUE THREAD

**Issue by IAMGGKK** [xdspacelab/openvslam#17]
It looks like ORBSLAM2, but change the form. I want to know if you speed up the process. Thanks！

**Comment by kensakurada** [comment]
Thank you for your interest in our project. As mentioned in [#15](https://github.com/xdspacelab/openvslam/issues/15), we will upload the preprint version of our OpenVSLAM paper, in which the processing time for the monocular setup is evaluated. Please use it as a reference. In the future, we will also evaluate the processing time for the stereo case. 

Or, you can measure mean and median tracking times on your machine using the example programs with benchmarking datasets such as EuRoC MAV dataset.
https://github.com/raulmur/ORB_SLAM2/blob/55d0970bb0f0d73dec0b4eddc31c654e6ca58eb7/Examples/Stereo/stereo_euroc.cc#L183
https://github.com/xdspacelab/openvslam/blob/36b3c4728c45f97e20ada6db1fae9e98b0b25369/example/run_euroc_slam.cc#L277
We recommend to measure them several times.
