### ISSUE TITLE
Installation for Windows 10

### ISSUE THREAD

**Issue by viet2411** [xdspacelab/openvslam#178]
Hello everyone,
Can anyone show me step by step of installing this framework on Windows 10? I had read the installation document but still can not figure out how to install this correctly
Thank you and best regards.

**Comment by vwvw** [comment]
Where are you stuck at? Are you running Docker or WSL?

**Comment by saweer** [comment]
@viet2411 
I found this article: https://qiita.com/na0ki_ikeda/items/2310dc8dd70713de98e1
It is written in Japanese, but I was able to understand it after translating to English with Google Translate.

**Comment by valeriob** [comment]
Hi @viet2411 
i was able to compile it for windows thanks to this repo https://github.com/reunanen/openvslam-build-vs it saved me sooo much time !

**Comment by shinsumicco** [comment]
@viet2411 
Would you try this?
https://github.com/shinsumicco/openvslam-on-msvc/
