### ISSUE TITLE
Does this support 360-degree stitching after image input?

### ISSUE THREAD

**Issue by hunkyu** [xdspacelab/openvslam#18]
Hello, I tried it. I don't know if the equirectangular piece supports the result of the image stitching after multiple cameras as the input of the system. Of course, the inner parameters after stitching have been calibrated.

**Comment by shinsumicco** [comment]
Thank you for your interest.
Our system currently supports equirectangular images even which are combined of multiple images.
In fact, the sample equirectangular video files we provide for the tutorial are created from **dual fisheye** movies like [this](https://developers.theta360.com/intl/common/img/dualfisheye.bmp).
Does that make sense?

**Comment by hunkyu** [comment]
![2019-05-24 17-19-22屏幕截图](https://user-images.githubusercontent.com/20533364/58317427-51679a00-7e48-11e9-9ddd-b98ec57b7d4f.png)
Camera.name: "RICOH THETA S 960"
Camera.setup: "monocular"
Camera.model: "equirectangular"

Camera.fps: 10.0
Camera.cols: 7168
Camera.rows: 930

Camera.color_order: "RGB"

#================#
# ORB Parameters #
#================#

Feature.max_num_keypoints: 2000
Feature.scale_factor: 1.2
Feature.num_levels: 8
Feature.ini_fast_threshold: 20
Feature.min_fast_threshold: 7
Feature.mask_rectangles:
  - [0.0, 1.0, 0.0, 0.1]
  - [0.0, 1.0, 0.84, 1.0]
  - [0.0, 0.2, 0.7, 1.0]
  - [0.8, 1.0, 0.7, 1.0]
I can't complete initialization with my own panoramic image.What do you think is the cause?

**Comment by hunkyu** [comment]
I changed Camera.fps to 30, which can be initialized normally, but I found that I did not complete the closed loop, and the estimation in the z direction is not accurate.

**Comment by shinsumicco** [comment]
Could you add margins on the top and on the bottom of images to make them be **2:1**?
Like this:

![Untitled Diagram](https://user-images.githubusercontent.com/17759682/58363886-67c43300-7ee6-11e9-8ff7-943c7d42a36e.png)

Accordingly adjust the `mask_rectangles` of the config file:

```
Feature.mask_rectangles:
- [0.0, 1.0, 0.0, 0.37]
- [0.0, 1.0, 0.63, 1.0]
```

If tracking failed soon after initialization, please downsize images to ~2K size.
And please confirm that the projection model of the camera you used for capturing is equirectangular.

**Comment by hunkyu** [comment]
![2019-05-25 18-17-54屏幕截图](https://user-images.githubusercontent.com/20533364/58368025-7c6dee80-7f19-11e9-9bce-7bf1a07b8fde.png)
After the change, it is really better! But the gesture displayed in pangolin is very strange, the posture of the camera is no longer right.

**Comment by hunkyu** [comment]
Feel that the heading angle has a fixed deviation

**Comment by shinsumicco** [comment]
I'm glad to hear that!

The camera poses displayed in the pangolin viewer seem to be correct. It is because the front direction of your camera is diagonal to the moving direction.
The front direction of the equirectangular camera model we implemented is defined as the center of an image. The center of your input image is not the moving direction, isn't it?

**Comment by hunkyu** [comment]
![image](https://user-images.githubusercontent.com/20533364/58372432-b3f78d80-7f4f-11e9-9daa-9350146bfe02.png)
The third part of my image is the direction of movement of the camera, which is right in front.

**Comment by hunkyu** [comment]
![2019-05-26 02-24-44屏幕截图](https://user-images.githubusercontent.com/20533364/58373283-3e46ee00-7f5e-11e9-9227-195157246a09.png)
I tested the effect of relocation, the effect is very good, I don't know if it works normally under different lighting changes! Also, I found out why your relocation program is so costly, up to 400%. Can you analyze the specific reasons? I feel that the positioning program multi-threading is to track the association with dbow parsing, and does not need to create local maps and closed-loop detection.

**Comment by hunkyu** [comment]
What is the basis for the Feature.mask_rectangles setting? @shinsumicco
