### ISSUE TITLE
Interface for a webstreaming webcam

### ISSUE THREAD

**Issue by dredystyle** [xdspacelab/openvslam#187]
Hello,

is there an interface to capture a webstreaming camera from another pc?

**Comment by shinsumicco** [comment]
Hi, @dredystyle .
OpenVSLAM doesn't have any interface to capture network streaming videos.
You will do it by capturing a stream with [FFmpeg](https://www.ffmpeg.org/) or [RTMPDump](https://rtmpdump.mplayerhq.hu/) and pass image to the OpenVSLAM system.

**Comment by shinsumicco** [comment]
Hi, @dredystyle .
OpenVSLAM doesn't have any interface to capture network streaming videos.
You will do it by capturing a stream with [FFmpeg](https://www.ffmpeg.org/) or [RTMPDump](https://rtmpdump.mplayerhq.hu/) and pass image to the OpenVSLAM system.
