### ISSUE TITLE
[feature] Allow to create `openvslam::config` object without config file

### ISSUE THREAD

**Issue by m-pilia** [xdspacelab/openvslam#198]
Hi, thanks for this great project!

I think it would be useful to add the possibility to create an `openvslam::config` object from a `YAML::Node` object.

Currently, the [only way](https://github.com/xdspacelab/openvslam/blob/510a56c4a5b/src/openvslam/config.h#L14) to create a `openvslam::config` object is by reading the configuration from a YAML file. If the user wants to create an `openvslam::config` reading the calibration parameters directly from a camera, the following steps are required:
1. read the calibration parameters from a camera API
2. put them in a `YAML::Node` object
3. dump the `YAML::Node` to a temporary file
4. create an `openvslam::config` object from the temporary file

If it was possible to create the `openvslam::config` from a `YAML::Node`, it would allow to avoid the extra step and the need for a temporary file:
1. read the calibration parameters from a camera API
2. put them in a `YAML::Node` object
3. create the configuration from the `YAML::Node`

**Comment by shinsumicco** [comment]
@m-pilia 
Sorry for the late reply and thank you for kind PR!
I think that the constructor you've newly appended is useful for such a situation.
I'll merge the PR soon after checking proper behavior.
Thanks again!
