### ISSUE TITLE
Can i run SLAM without orb_vocab.dbow2? What will happen then?

### ISSUE THREAD

**Issue by SKioresku** [xdspacelab/openvslam#207]

**Comment by Shashika007** [comment]
@SKioresku You have to choose either dbow2 or fbow as your bag of word library. In slam, we mostly use that for relocalization and loop closure purposes. openvslam won't work without a vocabulary file.

**Comment by SKioresku** [comment]
I wish to use openvslam for web application, but 40 mb is too much for downloading with mobile device. What can i do((?

**Comment by shinsumicco** [comment]
@SKioresku 
I recommend that you create own vocabulary whose size is smaller than the one we provide.
Vocabulary size is mainly influenced by parameters for vocabulary creation.

**Comment by SKioresku** [comment]
Can i use DBoW3 for vocabulary creation or i need to use DBoW2 vertion of shincumicco? What version is better and compatible with openvslam?

**Comment by Shashika007** [comment]
@SKioresku you can use DBoW3, but in order to use that, you have to change code inside source also BoW loading function. Also, you can train your own BoW file eaither dbow2 or 3 . I suggest you to try FBoW which is already implemented inside openvslam.

**Comment by SKioresku** [comment]
Can i resize training images to resolution performing for tracking ( 640x480 )?

**Comment by SKioresku** [comment]
Thanks for the help)

**Comment by dzqiu** [comment]
Hello, I can't download Bovisa dataset from the torrent. Anyone can help me? Thanks.
