### ISSUE TITLE
Camera model option

### ISSUE THREAD

**Issue by D7823** [xdspacelab/openvslam#215]
Hi all,

Thanks for the repo. 
And I wonder what are the options for the camera model? I see perspective, fisheye, and equirectangular. What should I put into the camera config file if I am using a common stereo camera?

Thanks in advance.

Duncan

**Comment by klintan** [comment]
The perspective camera model (also called pinhole) is the most common one in webcameras etc, so my guess is that is what you are looking for even if it's a stereo camera.

**Comment by D7823** [comment]
I am using the stereoPi camera which using two Pi cameras. Should be the pinhole model as you said.
Thank you so much.
