### ISSUE TITLE
Possible tiny bug

### ISSUE THREAD

**Issue by SKioresku** [xdspacelab/openvslam#235]
It seems there is a small bug, showed in attached image.
![Безымянный](https://user-images.githubusercontent.com/18395805/73356288-0e00dd80-42ab-11ea-92e0-9320ebcb37dd.png)

**Comment by SKioresku** [comment]
![Безымянный](https://user-images.githubusercontent.com/18395805/73356269-03dedf00-42ab-11ea-8c10-f326c767b15a.png)

**Comment by shinsumicco** [comment]
@SKioresku 
Thank you for the report, but it is not a bug.
`angle_histogram` is a buffer to contain angle differences of matched feature points.
Size of each `bin` differs depending on the number of matches and how good matches are.
So we reserve each of the `bin` for 300 entries, which is enough to contain matching results in most cases.
