### ISSUE TITLE
Comments in Japanese

### ISSUE THREAD

**Issue by maltoseslope** [xdspacelab/openvslam#242]
Hi, thanks for your nice code! but the comments are in Japanese, could you please translate the comments to English?

**Comment by shinsumicco** [comment]
@maltoseslope 
Thanks for your interest in this project.
We are currently working on translating comments to English.
Thank you for your patience.

**Comment by shinsumicco** [comment]
@maltoseslope
Codes with English comments will be released in `develop` branch by the end of June.
Thank you for your patience!
