### ISSUE TITLE
How to compile and build a new executable program? 

### ISSUE THREAD

**Issue by D7823** [xdspacelab/openvslam#250]
Hi,

I did some changes to the example code run_video_slam.cc to work with a video captured by the stereo camera. I wonder how could I compile and build this new code without rebuilding the whole project?

Thanks in advance.

**Comment by shinsumicco** [comment]
I suggest that you should  add a source code file for the new executable at `
openvslam/example`, and then add an entry in `openvslam/example/CMakeLists.txt` to build it.
It enables that only the source files which are changed will be built.
Or, you can install OpenVSLAM lib (`libopenvslam.so`) on your environment and reference it from the new CMake project you create.
