### ISSUE TITLE
Installation of the openvslam problem

### ISSUE THREAD

**Issue by maxkhain** [xdspacelab/openvslam#257]
When i follow the steps of the installation and finish the building of the openvslam library there are no files like the ./run_kitti_slam
It looks like i didn't compile the example folder, all the Requirements have been installed and no error messages are popping when building.
Am i doing something wrong?

**Comment by Shashika007** [comment]
@maxkhain Where did you build the openvslam ? you can check inside the build folder ? if you build it correctly, the executable file should be include inside the build folder. Otherwise, you can check your cmakelist whether there's executable file added for run_kitti_slam
