### ISSUE TITLE
Localize spherical and perspective camera

### ISSUE THREAD

**Issue by xfarxod** [xdspacelab/openvslam#269]
Hello. Thanks for the awesome work!

This project is really cool.

But I have an issue when I try to localize perspective RGB image to map that was built by spherical camera.  I tried to change the config and retake photos several times. But it cannot localize images.

Is it possible to do localization with different camera models?

**Comment by RashidLadj** [comment]
Hi @xfarxod 
I have same Problem, you can check my issue #388 if we will have an answer

**Comment by xfarxod** [comment]
@RashidLadj Thank you for your response. I will check.
