### ISSUE TITLE
Docker running error

### ISSUE THREAD

**Issue by ucmmesa** [xdspacelab/openvslam#27]
Hello,

After I build the image using "docker build -t openvslam-desktop .",I got the prompt of:
Successfully built 45ee1756604a
Successfully tagged openvslam-destop:latest

And then,I input the command of "xhost +local:",the terminal window said:
non-network local connections being added to access control list

Next,I input the command of “docker run -it --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix/:/tmp/.X11-unix:ro openvslam-desktop”，but the terminal window said:
Unable to find image 'openvslam-desktop:latest' locally
docker: Error response from daemon: pull access denied for openvslam-desktop, repository does not exist or may require 'docker login'.
See 'docker run --help'.

What's wrong?

**Comment by shinsumicco** [comment]
It seems that `Successfully tagged openvslam-destop:latest` contains a typo. `k` is missing.
(`openvslam-desktop:latest` is correct.)

Would you check the results of `docker image ls` command?
