### ISSUE TITLE
Make error 

### ISSUE THREAD

**Issue by 95ImadEL** [xdspacelab/openvslam#270]
Hello,

Can you help me to solve this error. 
`
/usr/bin/ld: /usr/local/lib/libyaml-cpp.a(exceptions.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTVN4YAML9ExceptionE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
src/openvslam/CMakeFiles/openvslam.dir/build.make:1922: recipe for target 'lib/libopenvslam.so' failed
make[2]: *** [lib/libopenvslam.so] Error 1
CMakeFiles/Makefile2:138: recipe for target 'src/openvslam/CMakeFiles/openvslam.dir/all' failed
make[1]: *** [src/openvslam/CMakeFiles/openvslam.dir/all] Error 2
Makefile:140: recipe for target 'all' failed
make: *** [all] Error 2

 `

Thank you in advance :)

**Comment by Shashika007** [comment]
@95ImadEL libyaml-cpp library may be conflict between two versions. 
if you are running the ros version, try to link your yaml-cpp library from absolute path inside openvslam/ros/openvslam/src/CMakeList.txt. 

example : 

target_link_libraries(run_custom_slam PRIVATE        
${Pangolin_Viewer_LIB} ${Pangolin_LIBRARIES} "/home/your-username/yaml-cpp/build/libyaml-cpp.so" ${Boost_LIBRARIES})

If it does not help, please share how you build the openvslam. your cmake configuration.

**Comment by 95ImadEL** [comment]
Thank you @Shashika007 it solves the problem
