### ISSUE TITLE
Build openvslam on Jetson Nano

### ISSUE THREAD

**Issue by D7823** [xdspacelab/openvslam#279]
Hi,

I wonder is it possible to build the openvslam on a Nano? I tried to follow the installation procedure but comes out many errors. Would it be just because of the Ubuntu version issue (my nano is running the Ubuntu 18)?

Thanks in advance
Duncan

**Comment by kumpee** [comment]
I've installed it on my Jetson NANO this morning, and it works fine.

**Comment by dimaxano** [comment]
@kumpee Did you measure FPS? Or any feelings on that?

**Comment by elfelround** [comment]
@D7823 u following any guide? link?
