### ISSUE TITLE
Can't build ... Need Help.

### ISSUE THREAD

**Issue by minsoo5403** [xdspacelab/openvslam#297]
OS Version : Linux version 5.3.0-46-generic (buildd@lcy01-amd64-013) (gcc version 7.5.0 (Ubuntu 7.5.0-3ubuntu1~18.04))

I am getting the following error while building OpenVSLAM at the end of the document. I need help

git clone https://github.com/xdspacelab/openvslam
cd openvslam
mkdir build && cd build
cmake \
        -DBUILD_WITH_MARCH_NATIVE=ON \
        -DUSE_PANGOLIN_VIEWER=ON \
        -DUSE_SOCKET_PUBLISHER=OFF \
        -DUSE_STACK_TRACE_LOGGER=ON \
        -DBOW_FRAMEWORK=DBoW2 \
        -DBUILD_TESTS=ON \
        ..
make -j4

/usr/bin/ld: /usr/local/lib/libyaml-cpp.a(exceptions.cpp.o): relocation R_X86_64_PC32 against symbol `_ZTVN4YAML9ExceptionE' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
src/openvslam/CMakeFiles/openvslam.dir/build.make:1925: recipe for target 'lib/libopenvslam.so' failed
make[2]: *** [lib/libopenvslam.so] Error 1
CMakeFiles/Makefile2:138: recipe for target 'src/openvslam/CMakeFiles/openvslam.dir/all' failed
make[1]: *** [src/openvslam/CMakeFiles/openvslam.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by Shashika007** [comment]
@minsoo5403 Please refer  #270

**Comment by minsoo5403** [comment]
We've solved the problem. Thank you. :)
