### ISSUE TITLE
Unable to run the example

### ISSUE THREAD

**Issue by Zumbalamambo** [xdspacelab/openvslam#304]
It throws the following error while I'm trying to install,

```
> terminate called after throwing an instance of 'std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >'
> *** Aborted at 1588965076 (unix time) try "date -d @1588965076" if you are using GNU date ***
> PC: @     0x7f159dbdee97 gsignal
> *** SIGABRT (@0x3e800002a27) received by PID 10791 (TID 0x7f15a0c71000) from PID 10791; stack trace: ***
>     @     0x7f159fb92890 (unknown)
>     @     0x7f159dbdee97 gsignal
>     @     0x7f159dbe0801 abort
>     @     0x7f159e25a227 (unknown)
>     @     0x7f159e2655d6 (unknown)
>     @     0x7f159e265641 std::terminate()
>     @     0x7f159e2658d5 __cxa_throw
>     @     0x7f15a0382cf8 DBoW2::TemplatedVocabulary<>::loadFromBinaryFile()
>     @     0x7f15a03801b4 openvslam::system::system()
>     @     0x7f15a101aae6 mono_tracking()
>     @     0x7f15a10195d0 main
>     @     0x7f159dbc1b97 __libc_start_main
>     @     0x7f15a1019afa _start
> Aborted (core dumped)
```

I have built as follows,

> ` cmake     -DBUILD_WITH_MARCH_NATIVE=OFF     -DUSE_PANGOLIN_VIEWER=ON     -DUSE_SOCKET_PUBLISHER=OFF    -DUSE_STACK_TRACE_LOGGER=ON     -DBOW_FRAMEWORK=DBoW2     -DBUILD_TESTS=ON     ..`

**Comment by ymd-stella** [comment]
Is orb_vocab.dbow2 obtained by the procedure described in [simple_tutorial.rst](https://github.com/xdspacelab/openvslam/blob/master/docs/simple_tutorial.rst) located in the path specified after `-v` option?

**Comment by Zumbalamambo** [comment]
@ymd-stella, of course, it is there... :(

**Comment by ymd-stella** [comment]
@Zumbalamambo Please show me the command line to reproduce it.

**Comment by Zumbalamambo** [comment]
I have used this

`./run_video_localization -v ./orb_vocab/orb_vocab.dbow2 -m ./a_loc/video.mp4 -c ./a_loc/config.yaml --frame-skip 3 --no-sleep --map-db map.msg
`

**Comment by ymd-stella** [comment]
Why are you using run_video_localization? (Map required)
Has run_video_slam already been succeeded?

**Comment by ymd-stella** [comment]
Try executing `ls -s ./orb_vocab/orb_vocab.dbow2` to make sure the file exists and is correct.
(In my environment, the file size was 43332 bytes.)
