### ISSUE TITLE
interpreting output messagePack file

### ISSUE THREAD

**Issue by angussmitchell** [xdspacelab/openvslam#309]
Hi, I'm trying to interpret information from the generated map for post processing. Ideally I'd like access to the camera trajectory, and sparse cloud points. 

So far I've unpacked the binarized data using a messagePack python library. Now, exploring the data i get, it is not clear where the camera rotations and translations are stored, if they are stored at all. 

Viewing in the python debugger I get the following output:
![image](https://user-images.githubusercontent.com/22647548/81618205-319afe80-942a-11ea-8f60-91022a913230.png)

by plotting the 'pos_w' values inside the landmarks field I get plot of the sparse cloud (what I wanted), but I am still unable to find any camera rotations or translations. You can see this below:

![landmarks](https://user-images.githubusercontent.com/22647548/81618420-a837fc00-942a-11ea-9773-b2e5e435a603.png)

Some documentation on how to extract this information would be greatly appreciated.

**Comment by angussmitchell** [comment]
the keyframes item contains the camera pose and rotation. This is in TUM format.

**Comment by Zumbalamambo** [comment]
@angussmitchell how did you recover the pose and rotation matrix from TUM Format?

**Comment by angussmitchell** [comment]
More info on the TUM format can be found here:
https://github.com/MichaelGrupp/evo/wiki/Formats
