### ISSUE TITLE
Getting the docker image working with socket publisher instead of pangolin?

### ISSUE THREAD

**Issue by slamjammin** [xdspacelab/openvslam#32]
I would like to modify the docker image so the user can choose either pangolin or socket mode, but am running into an issue where with the socketio package.

There is no findsocketio.cmake file and the following package github package (https://github.com/socketio/socket.io-client-cpp) does not generate congig.cmake files.

Has anyone found a fix that doesn't require massive code changes / works with an automated build pipeline?

**Comment by shinsumicco** [comment]
Would you try [the modified version of `sio-client-cpp`](https://github.com/shinsumicco/socket.io-client-cpp)?

We will soon provide the instructions for the socket mode.
