### ISSUE TITLE
run_camera_slam error using realsense r200

### ISSUE THREAD

**Issue by chyohoo** [xdspacelab/openvslam#325]
Hi, I try to use the rgb camera on realsense r200 to provide the input frames. But the frame and mapper viewer is black and got this error:

> [2020-05-21 06:22:47.852] [I] startup SLAM system
> [2020-05-21 06:22:47.856] [I] start global optimization module
> [2020-05-21 06:22:47.858] [I] start mapping module
> Framebuffer with requested attributes not available. Using available framebuffer. You may see visual artifacts.fine
> QObject::startTimer: Timers cannot be started from another thread

**Comment by jagauthier** [comment]
I'm also going to be using a RealSense R200.  What is your platform?   I am using an Intel Aero, and here's what I had to do: (Assumes you're using Debian/Ubuntu ROS)


https://github.com/IntelRealSense/librealsense/tree/legacy

Make sure you check out the legacy branch:
`git clone --branch legacy https://github.com/IntelRealSense/librealsense.git`
Follow the instructions build it. 

You can then launch the ROS package:
`roslaunch realsense_camera r200_nodelet_default.launch `

And it will publish all the camera info.

**Comment by chyohoo** [comment]
> I'm also going to be using a RealSense R200. What is your platform? I am using an Intel Aero, and here's what I had to do: (Assumes you're using Debian/Ubuntu ROS)
> 
> https://github.com/IntelRealSense/librealsense/tree/legacy
> 
> Make sure you check out the legacy branch:
> `git clone --branch legacy https://github.com/IntelRealSense/librealsense.git`
> Follow the instructions build it.
> 
> You can then launch the ROS package:
> `roslaunch realsense_camera r200_nodelet_default.launch `
> 
> And it will publish all the camera info.

Thanks! I am not using the ROS but I have solved the problem. Thanks again.
