### ISSUE TITLE
Multiple fisheye camera cluster

### ISSUE THREAD

**Issue by ofx53** [xdspacelab/openvslam#327]
Hi, thanks for the project!

I am looking to implement OpenVSlam using 2 fisheye cameras pointing at the sides of a car.

Would there be a way to implement using 2 different video streams? There is almost no overlap between them.
Simply stitching them together induces errors when I run the software because of the camera distortion on the sides.

Thanks in advance!

**Comment by shinsumicco** [comment]
We plan to add the tracking algorithm for the multiple cameras (namely multi-camera model) to OpenVSLAM, but any schedule for it is undecided yet.
Thank you for sharing the feature request.
