### ISSUE TITLE
How to change the trajectory to "KITTI'' format?

### ISSUE THREAD

**Issue by aiyanxiao** [xdspacelab/openvslam#334]
I performed the openvslam in stereo Kitti datasets, but the camera's trajectory is dumping frame trajectory in "TUM" format from frame 0 to frame 1060. However, I want to compare it with the ground truth trajectory of Kitti, Could anyone help me make this ? Thanks very much!

**Comment by shinsumicco** [comment]
@aiyanxiao Please see [here](https://github.com/xdspacelab/openvslam/issues/244#issuecomment-636752482).
(Thanks for sharing the script : @IaroslavS)

**Comment by aiyanxiao** [comment]
> @aiyanxiao Please see [here](https://github.com/xdspacelab/openvslam/issues/244#issuecomment-636752482).
> (Thanks for sharing the script : @IaroslavS)

Thanks very much!
