### ISSUE TITLE
Camera IMU alignment

### ISSUE THREAD

**Issue by SKioresku** [xdspacelab/openvslam#355]
I have measurements from rotation sensor of mobile phone and i want to rotate SLAM coordinat system with according to rotation sensor data. But these coordinat systems have different directions and order of axis. First camera have identity rotation and i have rotation from sensor.  My formula is NewSlamRotMatr = OldSlamRotMatr * CamImuMatr * SensorRotMatr.  But i think that i am doing something wrong((

**Comment by shinsumicco** [comment]
**In the world-reference coordinate system**, we can acquire an interpolated rotation for the new frame with:
NewWorld2CamRot = CamToImuRot.T * ImuIntegratedRot * CamToImuRot * OldWorld2CamRot

**Comment by SKioresku** [comment]
Thank You very much!
