### ISSUE TITLE
Covariance on Pose 

### ISSUE THREAD

**Issue by rebellojason7** [xdspacelab/openvslam#359]
Hi all,

any idea how to recover the covariance on the pose of the camera either in slam or localization modes ?
Thanks

**Comment by shinsumicco** [comment]
You may use "covariance propagation" for recovering covariance of the estimated pose.
Described in Section 5.2 of Multiple View Geometry.

**Comment by rebellojason7** [comment]
I understand the math. My question was more on the lines of does openvslam spit out the covariance on the pose or even the covariance for each map point

**Comment by YujiElfahkrany** [comment]
@shinsumicco I checked here 
https://arxiv.org/abs/1910.01122 
but couldn't find anything about covariance propagation)
any clues?

**Comment by rebellojason7** [comment]
I think this is more of a g2o problem. You need to use the computeMarginals function on the frame vertex.

**Comment by raghakkrishnan** [comment]
How do we use computeMarginals() to compute the covariance?
