### ISSUE TITLE
different poses in the exact same street, even with prior map

### ISSUE THREAD

**Issue by YujiElfahkrany** [xdspacelab/openvslam#360]
![different_poses](https://user-images.githubusercontent.com/46124816/85190782-a8af9680-b2f6-11ea-8b7a-d1b6fbad1d83.png)

using prior map with mapping module enabled, resulted in the shown picture. slightly different poses in the same place, which means redundant keyframes were created. 
after I disabled mapping module could get consistent poses to the time of making the map.

**Comment by shinsumicco** [comment]
This is because some SLAM algorithms used in OpenVSLAM have randomness.

**Comment by YujiElfahkrany** [comment]
ok, closing this
