### ISSUE TITLE
TUM RGBD dataset tutorial instructions are missing in the docs

### ISSUE THREAD

**Issue by robertklee** [xdspacelab/openvslam#361]
The TUM RGBD dataset example instructions available [here](https://openvslam.readthedocs.io/en/master/example.html#tum-rgbd-dataset) has no instructions on how to use it.

**Comment by shinsumicco** [comment]
@robertklee Thank you for reporting the issue.
We currently don't have a time to append the instructions for TUM RGBD dataset to the document.
Thus I'll write it in my spare time.

Of course, we are welcome to your contribution to reinforce the document! :-)
