### ISSUE TITLE
Possible memory leak after landmark erasing

### ISSUE THREAD

**Issue by alessandroTorresani** [xdspacelab/openvslam#365]
When a landmark is marked to be erased: 

`landmark::prepare_for_erasing();`
`map_db_->erase_landmark(this);`

The pointer to the landmark is removed from the unordered_map `landmarks_` but the memory is not freed. This seems a memory leak because the pointer is lost but the memory allocation remains.

**Comment by shinsumicco** [comment]
@alessandroTorresani Thank you for reporting the issue.
We've already understood the memory leak caused in database class.
We will work on fixing it. Thanks!

**Comment by alessandroTorresani** [comment]
Your are welcome! :)
