### ISSUE TITLE
ROS support

### ISSUE THREAD

**Issue by JinglingZhu** [xdspacelab/openvslam#37]
Thanks for your work.
Do you have a development plan about ROS and IMU supporting?

**Comment by gitunit** [comment]
there is a README in most projects. let me point you to the right info: https://github.com/xdspacelab/openvslam#currently-working-on
you are welcome.

**Comment by JinglingZhu** [comment]
I certainly saw this in the README. I just want to know when these features are about to release.

**Comment by shinsumicco** [comment]
@JinglingZhu, @gitunit 
Thank you for your interest in this project.
We are currently working on ROS support. It will be released soon.

**Comment by shinsumicco** [comment]
ROS examples are now provided.
https://openvslam.readthedocs.io/en/master/ros_package.html
