### ISSUE TITLE
run_camera_slam on monocular camera unable to get any keypoints on any frames

### ISSUE THREAD

**Issue by asmaaelkeurti** [xdspacelab/openvslam#402]
First Issue:
I calibrated a monocular camera:

Camera.name: "None"
Camera.setup: "monocular"
Camera.model: "perspective"

Camera.fx: 1014.19649
Camera.fy: 1017.30420
Camera.cx: 908.764904
Camera.cy: 486.025563

Camera.k1: -0.38001772
Camera.k2: 0.68757292
Camera.p1: -0.00273771
Camera.p2: -0.004389
Camera.k3: -0.73852111

Camera.fps: 30.0  # please reconfigure according to your camera
Camera.cols: 1920
Camera.rows: 1080

i run ./run_camera_slam on orb_vocab with config above
In PangolinViewer , i cannot get any keyPoints on camera streaming picture. Where exactly i need to look up

Second Issue:
I also noticed in the code, run_camera_slam, when opencv open up camera, it doesn't specify the camera resolution. 

I add two line in the run_camera_slam.cc to set the height and width for the resolution and recompile the project.
is this the right way to fix?

**Comment by Neel125** [comment]
which camera are you using ? @asmaaelkeurti
