### ISSUE TITLE
xdg runtime error and have to terminate manually

### ISSUE THREAD

**Issue by Kelvinson** [xdspacelab/openvslam#43]
Hi, when I run the examples I came across following (maybe not) errors:

![runtime_error](https://user-images.githubusercontent.com/16152743/58630672-24830f00-82ae-11e9-94a0-262c9660ab61.png)

**_error: XDG_RUNTIME_DIR not set in the environment._**
[2019-05-30 11:19:22.978] [I] relocalization succeeded

(PangolinViewer: Frame Viewer:38): **_dbind-WARNING **: 11:19:22.997: Couldn't connect to accessibility bus: Failed to connect to socket /tmp/dbus-JCbpe99zuj: Connection refused
Gtk-Message: 11:19:23.022: Failed to load module "canberra-gtk-module"
Gtk-Message: 11:19:23.024: Failed to load module "canberra-gtk-module"_**

It seems look like graphics problem.  I already run the
 
```
"xhost + local:" before run the docker 

using --runtime=nvidia and x11 forwarding 

```
Although it can run as in the tutorial, but I have to terminate it manually, or it would stop at the last frame, is that normal? Should it stop when all the video ends? 

Thank you for your amazing work!

**Comment by shinsumicco** [comment]
> error: XDG_RUNTIME_DIR not set in the environment.

This warning occurs in our environment, too.
But I think it doesn't probably affect the behavior of the viewer.
Does the viewer launched in your environment work correctly?

> Although it can run as in the tutorial, but I have to terminate it manually, or it would stop at the last frame, is that normal? Should it stop when all the video ends?

Yes, it is normal behavior.
Could you try `--auto-term` option to terminate the viewer automatically?

**Comment by Kelvinson** [comment]
Thanks for your reply, yes the viewer works correctly.  I will try that!
