### ISSUE TITLE
Map-database (*.msg) extracted using msgpack python doesn't give correct localized coordinates.

### ISSUE THREAD

**Issue by geekykant** [xdspacelab/openvslam#434]
I am able to generate the localized mapping of the demo area accurately. However as per #87 The .csv plot that was generated lies in small fractional values.

The coordinates were in ranges of X in (-9, 8) and Y in(-8,1). I cannot exactly replicate the same localized map.
What's the get through?

**Plotting on Sheet**
![Screenshot 2020-08-30 at 6 00 17 PM](https://user-images.githubusercontent.com/27401142/91659046-ba799b00-eaea-11ea-8946-13586cb0d108.png)

**SocketViewer**
![Screenshot 2020-08-30 at 6 02 08 PM](https://user-images.githubusercontent.com/27401142/91659073-f3b20b00-eaea-11ea-967c-fe75432b8a70.png)

**Comment by fabisant** [comment]
You need to georeference the coordinates, you can use CloudCompare. You need to have at least 4 reference points.
https://www.youtube.com/watch?v=S32wy66e_0o

**Comment by JoaoAVDuarte** [comment]
> The coordinates were in ranges of X in (-9, 8) and Y in(-8,1)

In your 1st image the coordinates are mostly within that range though, the ones that don't fit in that range are some outliers that can be easily removed using something like Open3D: 
```python
import open3d as o3d

# Read data as o3d pointcloud
# ...

pcd, ind = pcd.remove_radius_outlier(nb_points=5, radius=0.1)

# ...
```

**Comment by ymd-stella** [comment]
This issue is caused by a lack of understanding of map.msg and the data in it.
This is not an OpenVSLAM issue.
If you want to treat it as an OpenVSLAM issue, you should propose a feature request to document the use of map.msg.
Otherwise, it should be handled at https://spectrum.chat/openvslam.
