### ISSUE TITLE
Map scale is incorrect

### ISSUE THREAD

**Issue by yyyutooo** [xdspacelab/openvslam#463]
I used a RICOH THETA Z1 to do the mapping (i.e. a monocular OpenVSLAM). However, no matter how many times I try, the size of the objects in the map created is smaller than the size of the real world objects.
As long as we are running monocular OpenVSLAM, is it inevitable that the map is not scaled correctly?

**Comment by ymd-stella** [comment]
Yes.

**Comment by ymd-stella** [comment]
Please use the community (https://spectrum.chat/openvslam/beginner) to help you with your questions.

**Comment by yyyutooo** [comment]
Thank you.
I just posted a question with similar content.

**Comment by ymd-stella** [comment]
Please close this issue.
