### ISSUE TITLE
can‘t compile openvslam

### ISSUE THREAD

**Issue by ngadminq** [xdspacelab/openvslam#466]
![image](https://user-images.githubusercontent.com/42403520/96839566-f5a9a200-147b-11eb-8253-155701583207.png)

**Comment by surfii3z** [comment]
Looks like you miss some dependencies?

Did you try [this](https://openvslam.readthedocs.io/en/master/installation.html#installing-for-linux)

`sudo apt install -y libyaml-cpp-dev libgoogle-glog-dev libgflags-dev`

**Comment by ngadminq** [comment]
@surfii3z thank you,now issues are emerging
![image](https://user-images.githubusercontent.com/42403520/96843900-6bfcd300-1481-11eb-9006-8b4c26ad4cf1.png)

**Comment by ngadminq** [comment]
@surfii3z how to deal it?
![image](https://user-images.githubusercontent.com/42403520/96845790-aa938d00-1483-11eb-883f-1d4ed4bebf52.png)

**Comment by ngadminq** [comment]
root@VM-4-17-ubuntu:/home/ubuntu/openvslam# make
[  1%] Linking CXX shared library ../../lib/libopenvslam.so
/usr/bin/ld: /usr/local/lib/libyaml-cpp.a(scanscalar.cpp.o): relocation R_X86_64_PC32 against symbol `_ZNK4YAML5RegEx14MatchUncheckedINS_16StreamCharSourceEEEiRKT_' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
src/openvslam/CMakeFiles/openvslam.dir/build.make:1950: recipe for target 'lib/libopenvslam.so' failed
make[2]: *** [lib/libopenvslam.so] Error 1
CMakeFiles/Makefile2:138: recipe for target 'src/openvslam/CMakeFiles/openvslam.dir/all' failed
make[1]: *** [src/openvslam/CMakeFiles/openvslam.dir/all] Error 2
Makefile:129: recipe for target 'all' failed
make: *** [all] Error 2
root@VM-4-17-ubuntu:/home/ubuntu/openvslam#

**Comment by ymd-stella** [comment]
Please read https://openvslam.readthedocs.io/en/master/installation.html
