### ISSUE TITLE
The maps created are tilted/rotated

### ISSUE THREAD

**Issue by mirellameelo** [xdspacelab/openvslam#467]
Hi. I already tried to run OpenvSLAM using real and virtual datasets, and in both, I'm having inclined maps. As follows, a print screen from the same map, but from different angles of view.

I'm plotting the point clouds simply using:
```
landmark_vector = my_keyframe->get_landmarks();
...
point_pos = landmark_vector.at(i)->get_pos_in_world();
```
In red, there is the odometry info, which is set to y = 0, but its orientation also follows this weird inclination.

![Captura de tela de 2020-10-28 08-47-10](https://user-images.githubusercontent.com/34249507/97468061-19e50300-1902-11eb-92ed-06d4cde78c0a.png)

Does anyone is facing this issue?

EDIT: I just built the OpenvSLAM version ("develop" branch) and ran it using the dataset (aist_living_lab_1). The map is aligned. Then, I just change the input frames and its respective config file (perspective camera model), and I have the same tilted map as before... Any guess why this is happening? 

Thanks in advance!

**Comment by mirellameelo** [comment]
Please refer to [this link](https://spectrum.chat/openvslam/general/why-my-map-is-rotated~fe9f5065-d857-410a-be7f-de481cf1de18).

**Comment by anthonymiglio** [comment]
Hi @mirellameelo ! I am facing the same issue and I posted my current finding at [link](https://spectrum.chat/openvslam/general/why-my-map-is-rotated~fe9f5065-d857-410a-be7f-de481cf1de18) in openvslam community.

If it interest you or you have the time, could you please check it out? Thanks
