### ISSUE TITLE
What causes the points to be dropped?

### ISSUE THREAD

**Issue by JockTokk** [xdspacelab/openvslam#480]
Hi!
Have you faced [this](https://github.com/UZ-SLAMLab/ORB_SLAM3/issues/188#issue-746389841) problem?
Thanks for reply!

**Comment by dimaxano** [comment]
Hi!
If I understood you correctly, this passage from ORB-SLAM paper should explain landmarks disappearing

![image](https://user-images.githubusercontent.com/14369906/100237328-dcdf5100-2f3f-11eb-90b9-6773ef07761a.png)

**Comment by JockTokk** [comment]
@dimaxano thanks. I'm not sure if this is the solution because only the points that are behind the camera disappear.

**Comment by ymd-stella** [comment]
The issue is not for OpenVSLAM.
I think it's good to ask at https://spectrum.chat/openvslam/general, but it's inappropriate to make an Issue here.

**Comment by JockTokk** [comment]
@ymd-stella ok, thanks.
