### ISSUE TITLE
RICOH Theta Z1 Real time

### ISSUE THREAD

**Issue by ryleymcc** [xdspacelab/openvslam#497]
I installed the drivers to run the ricoh theta over usb but I don't know how to find what camera number it is. I tried camera numbers 0-10 but all the program finds is my webcam.

**Comment by ymd-stella** [comment]
This is not OpenVSLAM issue, it's camera driver issue.
It is acceptable to ask questions at https://spectrum.chat/openvslam/beginner, but it is inappropriate to ask them here.
