### ISSUE TITLE
Landmark registration: rgb color is always set to (0,0,0)

### ISSUE THREAD

**Issue by jrodal98** [xdspacelab/openvslam#52]
Thank you for all of your great work!  In the `serialize_as_protobuf` method in the `data_serializer` class, I noticed that the rgb color of landmark objects is always set to (0,0,0):

```
const unsigned int rgb[] = {0, 0, 0};
// add to protocol buffers
auto landmark_obj = map.add_landmarks();
landmark_obj->set_id(id);
for (int i = 0; i < 3; i++) {
    landmark_obj->add_coords(pos[i]);
}
for (int i = 0; i < 3; i++) {
    landmark_obj->add_color(rgb[i]);
}
```
As a work around, I modified the `frame` constructors to optionally accept the colored image of the frame and use the first keypoint in `keypts_` to extract the bgr colors as a `cv::Vec3b` vector, which is then stored as a field in the frame class.  Then, I modified the `keyframe` constructor to copy the bgr colors from the `frame` object into its own field.  Then, in the `serialize_as_protobuf` method, I use the bgr colors stored in the reference keyframe of each landmark to obtain colors for a landmark.

Do you have plans of changing this behavior in the near future?  I'm not sure that my work around is correct, as I am not very familiar with the theory behind openvslam.

**Comment by rahuldeo2047** [comment]
Ref only: https://github.com/xdspacelab/openvslam/issues/157
