### ISSUE TITLE
-DUSE_SOCKET_PUBLISHER=ON  is build error

### ISSUE THREAD

**Issue by match08** [xdspacelab/openvslam#66]
[ 95%] Linking CXX shared library ../../lib/libsocket_publisher.so
[ 96%] Built target socket_publisher
[ 97%] Linking CXX shared library ../../lib/libpangolin_viewer.so
/usr/bin/ld: cannot find -lwayland-egl
/usr/bin/ld: cannot find -lEGL
collect2: error: ld returned 1 exit status
src/pangolin_viewer/CMakeFiles/pangolin_viewer.dir/build.make:232: recipe for target 'lib/libpangolin_viewer.so' failed
make[2]: *** [lib/libpangolin_viewer.so] Error 1
CMakeFiles/Makefile2:451: recipe for target 'src/pangolin_viewer/CMakeFiles/pangolin_viewer.dir/all' failed
make[1]: *** [src/pangolin_viewer/CMakeFiles/pangolin_viewer.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by shinsumicco** [comment]
Would you specify `-DUSE_PANGOLIN_VIEWER=OFF` for `cmake` if you plan on using the socket publisher?

**Comment by match08** [comment]
Thanks
