### ISSUE TITLE
Run my own fisheye camera

### ISSUE THREAD

**Issue by Blackshaddock** [xdspacelab/openvslam#75]
I am trying to get openvslam run my own fisheye camera, but it cannot be initializated, the fisheye video and configuration are as follows, could you tell me what to pay attention to when recording data?
![2019-07-10 16-55-24屏幕截图](https://user-images.githubusercontent.com/34537812/60956176-d6453f00-a334-11e9-9861-a7246069d6db.png)

![2019-07-10 16-55-53屏幕截图](https://user-images.githubusercontent.com/34537812/60956286-199fad80-a335-11e9-8711-7c53404faae7.png)

**Comment by Blackshaddock** [comment]
I have solved the problem

**Comment by rahuldeo2047** [comment]
how?
What was the setup for the parameters?
Using OpenCV camera parameters?

**Comment by ethanguo0327** [comment]
how do you fix that? @Blackshaddock

**Comment by fangxu622** [comment]
怎么解决的的``我遇到同样的问题了 @Blackshaddock

**Comment by Blackshaddock** [comment]
@fangxu622 你图片的分辨率太大了  提取特征点的时候 提取不到  你试试 把分别率降低点

**Comment by Blackshaddock** [comment]
> how?
> What was the setup for the parameters?
> Using OpenCV camera parameters?

maybe you can use the function resize to reduce the image resolution

**Comment by Blackshaddock** [comment]
@ethanguo0327 reduce the image resolution

**Comment by ethanguo0327** [comment]
> @ethanguo0327 reduce the image resolution

Thanks,I'll try
