### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [xdspacelab/openvslam#8]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") like the following.
* [config](https://github.com/xdspacelab/openvslam/blob/19fecdaee07fc87f8bda884af21ffa88986ad4bc/src/openvslam/config.cc#L45 "Constructor for config")
* [initializer::reset](https://github.com/xdspacelab/openvslam/blob/19fecdaee07fc87f8bda884af21ffa88986ad4bc/src/openvslam/initialize/initializer.cc#L25 "initializer::reset function")

**Comment by shinsumicco** [comment]
Thanks! I'll fix it.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/xdspacelab/openvslam/commit/70f34f6e16f7ef66949b8fbbbc97fc05e50007b5 "Removal of four unnecessary checks").
