### ISSUE TITLE
Triangulate undistorted key points instead of key points

### ISSUE THREAD

**Issue by CanCanZeng** [xdspacelab/openvslam#90]
Hi, I find that you create map point using key points rather than undistorted key points, is this a slip of the pen?

https://github.com/xdspacelab/openvslam/blob/76c3955d9db8dee24cfe9b6b60225b6bc74c2d81/src/openvslam/data/frame.cc#L210-L211

**Comment by shinsumicco** [comment]
It has no problem because `keypts_` and `undist_` have the same coordinates for stereo sequences.
This is because input images are stereo-rectified (= undistorted).

We'll fix the source code because it seems confusing.
Thanks!

**Comment by CanCanZeng** [comment]
yeah, you are right, I forgot that the image is undistorted.
